on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'mkdir secrets && echo "${{secrets.ANDROID_KEYSTORE_PASS}}" > secrets/pass.txt'
      - run: 'echo "${{secrets.ANDROID_KEY_BASE64}}" > secrets/base64.txt'
      - run: 'echo "${{secrets.FIREBASE_APP_ID}}" > secrets/firebase-id.txt'
      - run: 'echo "${{secrets.FIREBASE_TOKEN}}" > secrets/token.txt'                    
      - uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: secrets
